### ISSUE TITLE
Создать внутри компонента  Input пропс isError в зависимости от которого вешается модификатор _error

### ISSUE THREAD

**Issue by igooooood** [superandrei205/Mercury-React#20]
https://github.com/superandrei205/Mercury-React/blob/fbbfe8c050a8653e66b567596e0efb70b660b94a/src/components/LoginPage/LoginPage.js#L39

 Вся логика отображения касающаяся компонента, должна быть в нём самом

**Comment by igooooood** [comment]
Можно сделать так же, как с рендером компонента Error `hasError && "input_error"`.
Нужно ещё прокинуть пропс в том месте где ты используешь инпут иначе не будет работать
 `<Input isError={hasError} />`

**Comment by superandrei205** [comment]
исправил
