### ISSUE TITLE
Не критичные замечания

### ISSUE THREAD

**Issue by igooooood** [superandrei205/Mercury-React#23]
Всё что находится в файле index.js, я бы вынес в компонент App, а в index.js делал бы чисто рендер данного компонента.

Состояние page, в компоненте app всё таки заменил бы на булевое isLogin.

**Comment by akuznetsov-md** [comment]
> Состояние page, в компоненте app всё таки заменил бы на булевое isLogin.

Да, имеет смысл, но в конкретном тестовом задании не принципиально.

**Comment by akuznetsov-md** [comment]
> Всё что находится в файле index.js, я бы вынес в компонент App, а в index.js делал бы чисто рендер данного компонента.

Это сделано, так что можно закрыть ишью
