### ISSUE TITLE
Файлы компонента следует держать рядом друг с другом

### ISSUE THREAD

**Issue by akuznetsov-md** [superandrei205/Mercury-React#3]
В "классическом" подходе к разработке веб сайтов файлы часто разделяют по их содержимому: css, img, js. В этом случае весь сайт рассматривается как единая неделимая система (монолит).

При разработке с использованием компонентного подхода, приложение _собирается_ из самостоятельных изолированных друг от друга элементов. В этом случае каждый компонент должен иметь все необходимое для корректной работы: стили, верстка, картинки и т.д.

В твоем случае стоит выделить стили каждого компонента в отдельный файл и подключать его внутри компонента. Сам компонент в таком случае стоит представить в виде папки с набором необходимых файлов.

**Comment by superandrei205** [comment]
вроде по всем замечаниям поправил.
